(()=>{'use strict';
const D=window.PARAMETER_SWEEP,$=id=>document.getElementById(id),COLORS=['#147b70','#ba7037','#8470a7'],fmt=(x,d=3)=>Number.isFinite(x)?x.toFixed(d):'—',ci=x=>x?'['+x.map(v=>fmt(v)).join(', ')+']':'—';
let currentPair,currentCells,currentCell;
const search=new URLSearchParams(location.search);if(search.has('q'))$('sweep-q').value=search.get('q');
$('sweep-counts').innerHTML=`<div><strong>${D.pairs.filter(p=>p.cells).length} pairs</strong><span>Four values of q · seven values of α each</span></div><div><strong>${D.totalGeneratedRecordings.toLocaleString()}</strong><span>Generated · ${D.configurations.toLocaleString()} in primary plots</span></div><div><strong>${D.totalGeneratedChains} chains</strong><span>${D.completedCells} parameter/size cells · three primary chains each</span></div>`;
$('sweep-methods').textContent=D.statisticalNotes.join(' ');
function setupAlpha(preferred){const q=Number($('sweep-q').value),ps=D.pairs.filter(p=>p.q===q);$('sweep-alpha').innerHTML=ps.map(p=>`<option value="${p.alpha}">${p.alpha} · ${p.regime}</option>`).join('');const want=preferred??2+q/4;if(ps.some(p=>p.alpha===Number(want)))$('sweep-alpha').value=String(want);selectPair();}
function selectPair(){const q=Number($('sweep-q').value),a=Number($('sweep-alpha').value);currentPair=D.pairs.find(p=>p.q===q&&p.alpha===a);currentCells=D.results.filter(c=>c.key===currentPair.key);$('sweep-n').innerHTML=currentCells.map(c=>`<option value="${c.N}">${c.N}</option>`).join('');$('sweep-n').value=String(currentCells.at(-1).N);render();}
function currentPrediction(p){
 if(p.q===2)return {label:p.alpha<3?'Gaussian fractional field · exact':'Gaussian Brownian limit · exact',detail:p.alpha<3?`The finite field is Gaussian exactly. Predict the restricted Dirichlet fractional Gaussian limit with aₙ = n^${fmt((p.alpha-2)/2)}; a finite-size exponent below this power does not change the exact limiting law.`:p.alpha===3?'The finite field is Gaussian exactly. With aₙ = √(n/log n), the limiting field is ½B_D.':'The finite field is Gaussian exactly. With aₙ = √n, the limiting field is [4ζ(α−2)]⁻¹/²B_D.'};
 if(p.regime==='rough-mid'||p.regime==='rough-high')return {label:'Non-Gaussian rough limit · favored',detail:`Predict a non-Gaussian field under aₙ = n^${fmt(p.predicted.H)}, with a strictly positive limiting even-bump excess kurtosis. This excludes fractional Brownian motion. ${p.regime==='rough-high'?'The observed power is below the proposed H = 0.4, so that exponent remains provisional.':p.q===1.5?'Non-Gaussianity is resolved in the longer n = 512 run; H = ¼ remains a working guess because the fitted H is 0.222.':'The fitted power agrees with H = ¼.'} The full joint limiting law is not yet identified.`};
 if(p.regime==='diffusive')return {label:'Gaussian Brownian bridge · favored',detail:'Predict aₙ = √n and limiting field σ(q,α)B_D, with deterministic σ > 0. The size dependence, fourth moments and amplitude-free covariance ratios favor this prediction; the limiting σ is not identified.'};
 if(p.regime==='localized')return {label:'Gaussian fractional field · tentative',detail:'Tentatively predict aₙ = n⁻¹/⁸ and limiting field σ(q,1.75)G₁․₇₅. The Gaussian object is a random distribution with zero exterior. Residual fourth cumulants and drifting covariance ratios make this weaker than the rough and far-diffusive predictions.'};
 if(p.regime==='lower-critical')return {label:'Critical limit · unresolved',detail:`No limiting law or log power selected by the data here. The original hypothesis is a Gaussian distribution σ(q,2)G₂ with aₙ = (log n)^${fmt(p.predicted.logPower)}. The measured effective logarithm and residual non-Gaussianity leave that hypothesis provisional.`};
 if(p.regime==='upper-critical')return {label:'Critical limit · unresolved',detail:`No limiting law or log power selected by the data here. The original hypothesis is a Brownian bridge with aₙ = √n/(log n)^${fmt(1/p.q)}. The transition location itself remains provisional; this simulated point is not established to be critical.`};
 return {label:p.q===1.5?'Gaussian Brownian bridge · tentative':'Near-transition limit · unresolved',detail:p.q===1.5?'Tentatively predict a Brownian bridge with aₙ = √n: the fourth moments and covariance ratios move toward the Gaussian bridge, but the fitted H is still below ½. This point does not establish the transition location.':'The original candidate is a Brownian bridge with aₙ = √n. Detectable fourth cumulants remain above the proposed transition; the present data do not select between a slow approach to that Gaussian limit and a different transition picture.'};
}
function chart(id,series,{zero=false,logx=false,xlabel='',ylabel='',diagonal=false,hist=false}={}){
 const canvas=$(id),rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height,dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 const points=series.flatMap(s=>s.points),X=v=>logx?Math.log2(v):v;let xmin=Math.min(...points.map(p=>X(p.x))),xmax=Math.max(...points.map(p=>X(p.x))),ymin=Math.min(...points.map(p=>p.lo??p.y)),ymax=Math.max(...points.map(p=>p.hi??p.y));
 if(zero){ymin=Math.min(0,ymin);ymax=Math.max(0,ymax);}if(diagonal){ymin=Math.min(ymin,xmin);ymax=Math.max(ymax,xmax);}if(ymax===ymin)ymax=ymin+1;if(xmax===xmin)xmax=xmin+1;const margin=(ymax-ymin)*.1;ymin-=margin;ymax+=margin;
 const left=60,right=w-13,top=14,bottom=h-39,x=v=>left+(X(v)-xmin)/(xmax-xmin)*(right-left),y=v=>bottom-(v-ymin)/(ymax-ymin)*(bottom-top);
 ctx.font='10px -apple-system,sans-serif';ctx.lineWidth=1;
 for(let i=0;i<=4;i++){const v=ymin+(ymax-ymin)*i/4;ctx.strokeStyle='#e5e8df';ctx.beginPath();ctx.moveTo(left,y(v));ctx.lineTo(right,y(v));ctx.stroke();ctx.fillStyle='#687b72';ctx.textAlign='right';ctx.fillText(Math.abs(v)<.001&&v!==0?v.toExponential(1):Number(v.toPrecision(3)).toString(),left-7,y(v)+3);}
 let ticks=logx?[...new Set(points.map(p=>p.x))].sort((a,b)=>a-b):Array.from({length:5},(_,i)=>xmin+(xmax-xmin)*i/4);
 if(ticks.length>8)ticks=ticks.filter((_,i)=>i%Math.ceil(ticks.length/8)===0);
 ctx.textAlign='center';for(const v of ticks)ctx.fillText(logx?String(v):Number(v.toPrecision(3)).toString(),x(v),bottom+17);
 ctx.fillText(xlabel,(left+right)/2,h-4);ctx.textAlign='left';ctx.fillText(ylabel,4,10);
 if(zero&&ymin<0&&ymax>0){ctx.strokeStyle='#b3beb5';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(left,y(0));ctx.lineTo(right,y(0));ctx.stroke();ctx.setLineDash([]);}
 if(diagonal){ctx.strokeStyle='#9eaaa3';ctx.beginPath();ctx.moveTo(x(xmin),y(xmin));ctx.lineTo(x(xmax),y(xmax));ctx.stroke();}
 for(const s of series){ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineWidth=s.width||1.8;if(s.dashed)ctx.setLineDash([4,4]);ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(x(p.x),y(p.y)):ctx.moveTo(x(p.x),y(p.y)));if(!s.dots&&!s.bars)ctx.stroke();ctx.setLineDash([]);
  for(const p of s.points){if(s.bars){ctx.globalAlpha=.42;const bw=(right-left)/(xmax-xmin)*.24;ctx.fillRect(x(p.x)-bw/2,y(p.y),bw,y(0)-y(p.y));ctx.globalAlpha=1;}if(p.lo!==undefined){ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x(p.x),y(p.lo));ctx.lineTo(x(p.x),y(p.hi));ctx.moveTo(x(p.x)-3,y(p.lo));ctx.lineTo(x(p.x)+3,y(p.lo));ctx.moveTo(x(p.x)-3,y(p.hi));ctx.lineTo(x(p.x)+3,y(p.hi));ctx.stroke();}if(s.dots||p.lo!==undefined){ctx.beginPath();ctx.arc(x(p.x),y(p.y),2.7,0,Math.PI*2);ctx.fill();}}
 }
}
function render(){
 const p=currentPair,cs=currentCells,c=cs.find(c=>c.N===Number($('sweep-n').value)),projection=$('sweep-projection').value;currentCell=c;const fit=p.fits.f,scale=p.predicted,quality=c.quality;
 const critical=scale.logPower?` The proposed log power is ${fmt(scale.logPower)}; fitting that log power with H fixed at ${fmt(scale.H)} gives ${fmt(fit.logPower.estimate)} ${ci(fit.logPower.interval)}.`:'';
 const verdict=currentPrediction(p),largest=cs.at(-1);
 $('sweep-reading').innerHTML=`<div class="eyebrow">Current prediction · q = ${p.q}, α = ${p.alpha}</div><h2 id="sweep-verdict">${verdict.label}</h2><p>${verdict.detail}</p><p><strong>Evidence across the saved sizes:</strong> κ(f) = ${fmt(largest.stats.f.excess)} ${ci(largest.bootstrap.intervals.fExcess)} at the largest n = ${largest.N}. Fitted H = <strong>${fmt(fit.corrected.estimate)} ${ci(fit.corrected.interval)}</strong>, using n = ${fit.corrected.sizes.join(', ')}.${critical}</p><p class="sweep-small">The plots retain the original test scale aₙ = n<sup>${fmt(scale.H)}</sup>${scale.logPower?`(log n)<sup>${fmt(scale.logPower)}</sup>`:''}. ${scale.logPower?'The displayed H fit subtracts that proposed logarithm; it is not an uncorrected height exponent. ':''}The current prediction uses the full size series, independently of the selected display size.</p><p class="${quality.adequate?'sweep-good':'sweep-warning'}">Selected n = ${c.N}: κ(f) = ${fmt(c.stats.f.excess)} ${ci(c.bootstrap.intervals.fExcess)}. ${quality.adequate?'The displayed smooth observables pass the mixing screen.':'Mixing or effective sample count does not pass the full screen; interpret this cell cautiously.'}</p>`;
 const variance=[{color:COLORS[0],points:cs.map(c=>({x:c.N,y:c.normalization.variance,lo:c.normalization.varianceInterval[0],hi:c.normalization.varianceInterval[1]}))}];
 if(p.q===2)variance.push({color:'#5086ba',dashed:true,points:cs.filter(c=>c.gaussianControl).map(c=>({x:c.N,y:c.gaussianControl.exactVariance*c.normalization.factor**2}))});
 chart('sweep-variance',variance,{logx:true,xlabel:'Box radius n',ylabel:'Variance'});
 chart('sweep-kurtosis',['f','g','narrow'].map((k,i)=>({color:COLORS[i],points:cs.map(c=>({x:c.N,y:c.stats[k].excess,lo:c.bootstrap.intervals[k+'Excess'][0],hi:c.bootstrap.intervals[k+'Excess'][1]}))})),{zero:true,logx:true,xlabel:'Box radius n',ylabel:'Excess κ'});
 chart('sweep-histogram',[{color:COLORS[0],bars:true,points:c.plots[projection].histogram.map(p=>({x:p.x,y:p.density}))},{color:'#6988a8',points:Array.from({length:121},(_,i)=>({x:-6+i*.1,y:Math.exp(-.5*(-6+i*.1)**2)/Math.sqrt(2*Math.PI)}))}],{zero:true,xlabel:'Standardized pairing',ylabel:'Density'});
 chart('sweep-qq',[{color:COLORS[0],dots:true,points:c.plots[projection].qq.map(p=>({x:p.normal,y:p.empirical}))}],{diagonal:true,xlabel:'Normal quantile',ylabel:'Empirical quantile'});
 chart('sweep-traces',c.chains.map((r,i)=>({color:COLORS[i],width:1,points:r.trace.map((y,j)=>({x:j*40,y}))})),{xlabel:'Retained recording index',ylabel:'Yₙ(f)'});
 chart('sweep-profiles',c.chains.map((r,i)=>({color:COLORS[i],width:1,points:r.profile})),{xlabel:'Position i/n',ylabel:'φ(i) / aₙ'});
 $('sweep-size-table').innerHTML=cs.map(r=>`<tr><td>${r.N}</td><td>${r.sampler==='cluster'?'Cluster + Metropolis':'Metropolis'}</td><td>${fmt(r.normalization.variance,5)}</td><td>${fmt(r.stats.f.excess)} ${ci(r.bootstrap.intervals.fExcess)}</td><td>${fmt(r.stats.g.excess)}</td><td>${fmt(r.joint.wick)} ${ci(r.bootstrap.intervals.wick)}</td><td>${Math.round(r.diagnostics.f.ess)} / ${Math.round(r.diagnostics.f.essFourth)}</td><td>${fmt(r.diagnostics.f.rhat,4)} / ${fmt(r.diagnostics.f.rhatSquared,4)}</td></tr>`).join('');
 const metrics=[['Var(g)/Var(f)','gfVarianceRatio'],['Var(narrow)/Var(f)','narrowfVarianceRatio'],['Corr(left,right)','leftRightCorrelation']];
 $('sweep-joint').innerHTML=`<div class="sweep-table"><table><thead><tr><th>Shape statistic</th><th>Measured, 95% interval</th><th>Brownian bridge</th><th>${p.q===2?'Exact finite Gaussian':'Fractional Gaussian comparison'}</th></tr></thead><tbody>${metrics.map(([name,k])=>`<tr><td>${name}</td><td>${fmt(c.joint[k])} ${ci(c.bootstrap.intervals[k])}</td><td>${fmt(c.brownianShape[k])}</td><td>${fmt((c.gaussianControl?.shape??c.gaussianAnalogy)?.[k])}</td></tr>`).join('')}</tbody></table></div><p class="sweep-small">The fractional comparison uses the finite zero-exterior Gaussian field${c.gaussianAnalogy?' at exponent α = '+fmt(c.gaussianAnalogy.alpha):''}. Ratios remove an unknown deterministic amplitude. A covariance match would still leave higher moments to test.</p><p>q E[energy]/(2n+1) = <strong>${fmt(c.energy.qMeanPerDimension,4)}</strong>; q Var(energy)/(2n+1) = <strong>${fmt(c.energy.qVariancePerDimension,4)}</strong> (both should equal 1). ${c.gaussianControl?`Measured/exact Gaussian variance = <strong>${fmt(c.gaussianControl.varianceRatio)} ${ci(c.gaussianControl.varianceRatioInterval)}</strong>.`:''}</p><p>κ(f) − κ(g) = ${fmt(c.joint.excessDifference)} ${ci(c.bootstrap.intervals.excessDifference)}. The residual for an independent common scalar Gaussian mixture is ${fmt(c.joint.commonScaleResidual)} ${ci(c.bootstrap.intervals.commonScaleResidual)} (zero under that hypothesis).</p><p class="sweep-small">Kurtosis intervals with block lengths 250 / 500 / 1000 retained recordings: ${ci(c.bootstrap.sensitivity[0].intervals.fExcess)} / ${ci(c.bootstrap.intervals.fExcess)} / ${ci(c.bootstrap.sensitivity[1].intervals.fExcess)}.</p>`;
 if(c.originalMetropolis){const old=c.originalMetropolis;$('sweep-joint').insertAdjacentHTML('beforeend',`<h3>Why the sampler extension matters</h3><div class="sweep-table"><table><thead><tr><th>Run at n = ${c.N}</th><th>Recordings</th><th>κ(f), 95% interval</th><th>ESS(f)</th><th>R̂(f)</th></tr></thead><tbody><tr><td>Original Metropolis</td><td>${old.count.toLocaleString()}</td><td>${fmt(old.stats.f.excess)} ${ci(old.kurtosisInterval)}</td><td>${Math.round(old.diagnostics.f.ess)}</td><td>${fmt(old.diagnostics.f.rhat,4)}</td></tr><tr><td>Independent cluster extension</td><td>${c.count.toLocaleString()}</td><td>${fmt(c.stats.f.excess)} ${ci(c.bootstrap.intervals.fExcess)}</td><td>${Math.round(c.diagnostics.f.ess)}</td><td>${fmt(c.diagnostics.f.rhat,4)}</td></tr></tbody></table></div><p class="sweep-small">Both samplers target the same measure. The primary plots use the cluster extension; all original recordings and their analyses remain downloadable.</p>`);}
}
$('sweep-all-table').innerHTML=D.pairs.filter(p=>p.fits).map(p=>{const c=D.results.filter(c=>c.key===p.key).at(-1);return `<tr><td><button data-pair="${p.key}">${p.q}</button></td><td><button data-pair="${p.key}">${p.alpha}</button></td><td>${currentPrediction(p).label}</td><td>${p.largestN}</td><td>${fmt(p.predicted.H)}</td><td>${fmt(p.fits.f.corrected.estimate)} ${ci(p.fits.f.corrected.interval)}</td><td>${fmt(c.stats.f.excess)} ${ci(c.bootstrap.intervals.fExcess)}</td><td>${fmt(c.stats.g.excess)}</td><td>${Math.round(c.diagnostics.f.ess)}</td><td class="${c.quality.adequate?'sweep-good':'sweep-warning'}">${c.quality.adequate?'Passes screen':'Check diagnostics'}</td></tr>`;}).join('');
$('sweep-all-table').onclick=e=>{const button=e.target.closest('[data-pair]');if(!button)return;const p=D.pairs.find(p=>p.key===button.dataset.pair);$('sweep-q').value=String(p.q);setupAlpha(p.alpha);$('selected-experiment').scrollIntoView({behavior:'smooth'});};
$('sweep-q').onchange=()=>setupAlpha();$('sweep-alpha').onchange=selectPair;$('sweep-n').onchange=render;$('sweep-projection').onchange=render;
setupAlpha(search.get('alpha')??undefined);let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(render,120);});
window.SWEEP_UI={get selected(){return {key:currentPair.key,N:currentCell.N};},render};
})();
